/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : StreamingClientFSM.sm
 */


//
// Author: Prashant Srinivasan
//


package com.sfdc.http.smc;

import com.ning.http.client.Cookie;
import com.ning.http.client.Response;

import java.io.PrintStream;
import java.util.List;
import java.util.concurrent.Future;

public class StreamingClientFSMContext
        extends statemap.FSMContext {
//---------------------------------------------------------------
// Member methods.
//

    public StreamingClientFSMContext(StreamingClient owner) {
        super(FSM.Initial);

        _owner = owner;
    }

    public StreamingClientFSMContext(StreamingClient owner, StreamingClientState initState) {
        super(initState);

        _owner = owner;
    }

    public synchronized void enterStartState() {
        getState().Entry(this);
        return;
    }

    public synchronized void onConnectComplete() {
        _transition = "onConnectComplete";
        getState().onConnectComplete(this);
        _transition = "";
        return;
    }

    public synchronized void onFinishedScenario() {
        _transition = "onFinishedScenario";
        getState().onFinishedScenario(this);
        _transition = "";
        return;
    }

    public synchronized void onHandshakeComplete(List<Cookie> cookies, String clientId) {
        _transition = "onHandshakeComplete";
        getState().onHandshakeComplete(this, cookies, clientId);
        _transition = "";
        return;
    }

    public synchronized void onReconnectRequest() {
        _transition = "onReconnectRequest";
        getState().onReconnectRequest(this);
        _transition = "";
        return;
    }

    public synchronized void onStartingConnect(Future<Response> future) {
        _transition = "onStartingConnect";
        getState().onStartingConnect(this, future);
        _transition = "";
        return;
    }

    public synchronized void onStartingHandshake(Future<Response> future) {
        _transition = "onStartingHandshake";
        getState().onStartingHandshake(this, future);
        _transition = "";
        return;
    }

    public synchronized void onStartingSubscribe(Future<Response> future) {
        _transition = "onStartingSubscribe";
        getState().onStartingSubscribe(this, future);
        _transition = "";
        return;
    }

    public synchronized void onSubscribeComplete() {
        _transition = "onSubscribeComplete";
        getState().onSubscribeComplete(this);
        _transition = "";
        return;
    }

    public StreamingClientState getState()
            throws statemap.StateUndefinedException {
        if (_state == null) {
            throw (
                    new statemap.StateUndefinedException());
        }

        return ((StreamingClientState) _state);
    }

    protected StreamingClient getOwner() {
        return (_owner);
    }

    public void setOwner(StreamingClient owner) {
        if (owner == null) {
            throw (
                    new NullPointerException(
                            "null owner"));
        } else {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private StreamingClient _owner;

    public static abstract class StreamingClientState
            extends statemap.State {
        //-----------------------------------------------------------
        // Member methods.
        //

        protected StreamingClientState(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
        }

        protected void Exit(StreamingClientFSMContext context) {
        }

        protected void onConnectComplete(StreamingClientFSMContext context) {
            Default(context);
        }

        protected void onFinishedScenario(StreamingClientFSMContext context) {
            Default(context);
        }

        protected void onHandshakeComplete(StreamingClientFSMContext context, List<Cookie> cookies, String clientId) {
            Default(context);
        }

        protected void onReconnectRequest(StreamingClientFSMContext context) {
            Default(context);
        }

        protected void onStartingConnect(StreamingClientFSMContext context, Future<Response> future) {
            Default(context);
        }

        protected void onStartingHandshake(StreamingClientFSMContext context, Future<Response> future) {
            Default(context);
        }

        protected void onStartingSubscribe(StreamingClientFSMContext context, Future<Response> future) {
            Default(context);
        }

        protected void onSubscribeComplete(StreamingClientFSMContext context) {
            Default(context);
        }

        protected void Default(StreamingClientFSMContext context) {
            if (context.getDebugFlag() == true) {
                PrintStream str =
                        context.getDebugStream();

                str.println(
                        "TRANSITION   : Default");
            }

            throw (
                    new statemap.TransitionUndefinedException(
                            "State: " +
                                    context.getState().getName() +
                                    ", Transition: " +
                                    context.getTransition()));
        }

        //-----------------------------------------------------------
        // Member data.
        //
    }

    /* package */ static abstract class FSM {
        //-----------------------------------------------------------
        // Member methods.
        //

        //-----------------------------------------------------------
        // Member data.
        //

        //-------------------------------------------------------
        // Constants.
        //
        public static final FSM_Initial Initial =
                new FSM_Initial("FSM.Initial", 0);
        public static final FSM_Handshaking Handshaking =
                new FSM_Handshaking("FSM.Handshaking", 1);
        public static final FSM_Handshaken Handshaken =
                new FSM_Handshaken("FSM.Handshaken", 2);
        public static final FSM_Subscribing Subscribing =
                new FSM_Subscribing("FSM.Subscribing", 3);
        public static final FSM_Subscribed Subscribed =
                new FSM_Subscribed("FSM.Subscribed", 4);
        public static final FSM_Connected Connected =
                new FSM_Connected("FSM.Connected", 5);
        public static final FSM_Disconnected Disconnected =
                new FSM_Disconnected("FSM.Disconnected", 6);
        public static final FSM_Reconnecting Reconnecting =
                new FSM_Reconnecting("FSM.Reconnecting", 7);
        public static final FSM_Done Done =
                new FSM_Done("FSM.Done", 8);
        public static final FSM_ClientAborted ClientAborted =
                new FSM_ClientAborted("FSM.ClientAborted", 9);
        private static final FSM_Default Default =
                new FSM_Default("FSM.Default", -1);

    }

    protected static class FSM_Default
            extends StreamingClientState {
        //-----------------------------------------------------------
        // Member methods.
        //

        protected FSM_Default(String name, int id) {
            super(name, id);
        }
        //-----------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Initial
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Initial(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
            StreamingClient ctxt = context.getOwner();

            ctxt.startHandshake();
            return;
        }

        protected void onStartingHandshake(StreamingClientFSMContext context, Future<Response> future) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Initial");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Initial.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Initial.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Initial.onStartingHandshake(Future<Response> future)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Initial.onStartingHandshake(Future<Response> future)");
            }

            context.setState(FSM.Handshaking);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Handshaking.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Handshaking.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Handshaking
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Handshaking(String name, int id) {
            super(name, id);
        }

        protected void onHandshakeComplete(StreamingClientFSMContext context, List<Cookie> cookies, String clientId) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Handshaking");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Handshaking.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Handshaking.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Handshaking.onHandshakeComplete(List<Cookie> cookies, String clientId)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Handshaking.onHandshakeComplete(List<Cookie> cookies, String clientId)");
            }

            context.setState(FSM.Handshaken);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Handshaken.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Handshaken.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Handshaken
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Handshaken(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
            StreamingClient ctxt = context.getOwner();

            ctxt.startSubscribe();
            return;
        }

        protected void onStartingSubscribe(StreamingClientFSMContext context, Future<Response> future) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Handshaken");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Handshaken.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Handshaken.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Handshaken.onStartingSubscribe(Future<Response> future)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Handshaken.onStartingSubscribe(Future<Response> future)");
            }

            context.setState(FSM.Subscribing);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Subscribing.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Subscribing.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Subscribing
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Subscribing(String name, int id) {
            super(name, id);
        }

        protected void onSubscribeComplete(StreamingClientFSMContext context) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Subscribing");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Subscribing.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Subscribing.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Subscribing.onSubscribeComplete()");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Subscribing.onSubscribeComplete()");
            }

            context.setState(FSM.Subscribed);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Subscribed.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Subscribed.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Subscribed
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Subscribed(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
            StreamingClient ctxt = context.getOwner();

            ctxt.startConnect();
            return;
        }

        protected void onStartingConnect(StreamingClientFSMContext context, Future<Response> future) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Subscribed");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Subscribed.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Subscribed.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Subscribed.onStartingConnect(Future<Response> future)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Subscribed.onStartingConnect(Future<Response> future)");
            }

            context.setState(FSM.Connected);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Connected.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Connected.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Connected
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Connected(String name, int id) {
            super(name, id);
        }

        protected void onConnectComplete(StreamingClientFSMContext context) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Connected");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Connected.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Connected.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Connected.onConnectComplete()");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Connected.onConnectComplete()");
            }

            context.setState(FSM.Disconnected);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Disconnected.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Disconnected.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Disconnected
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Disconnected(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
            StreamingClient ctxt = context.getOwner();

            ctxt.shouldWeReconnect();
            return;
        }

        protected void onFinishedScenario(StreamingClientFSMContext context) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Disconnected");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Disconnected.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Disconnected.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Disconnected.onFinishedScenario()");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Disconnected.onFinishedScenario()");
            }

            context.setState(FSM.Done);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Done.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Done.Entry(context)");
            }
            return;
        }

        protected void onReconnectRequest(StreamingClientFSMContext context) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Disconnected");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Disconnected.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Disconnected.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Disconnected.onReconnectRequest()");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Disconnected.onReconnectRequest()");
            }

            context.setState(FSM.Reconnecting);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Reconnecting.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Reconnecting.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Reconnecting
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Reconnecting(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
            StreamingClient ctxt = context.getOwner();

            ctxt.startConnect();
            return;
        }

        protected void onStartingConnect(StreamingClientFSMContext context, Future<Response> future) {

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("LEAVING STATE   : FSM.Reconnecting");
            }
            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE EXIT     : FSM.Reconnecting.Exit(context)");
            }

            (context.getState()).Exit(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER EXIT      : FSM.Reconnecting.Exit(context)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("ENTER TRANSITION: FSM.Reconnecting.onStartingConnect(Future<Response> future)");
            }

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("EXIT TRANSITION : FSM.Reconnecting.onStartingConnect(Future<Response> future)");
            }

            context.setState(FSM.Connected);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("BEFORE ENTRY    : FSM.Connected.Entry(context)");
            }

            (context.getState()).Entry(context);

            if (context.getDebugFlag() == true) {
                PrintStream str = context.getDebugStream();

                str.println("AFTER ENTRY     : FSM.Connected.Entry(context)");
            }
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_Done
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_Done(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
            StreamingClient ctxt = context.getOwner();

            ctxt.clientDone();
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }

    private static final class FSM_ClientAborted
            extends FSM_Default {
        //-------------------------------------------------------
        // Member methods.
        //

        private FSM_ClientAborted(String name, int id) {
            super(name, id);
        }

        protected void Entry(StreamingClientFSMContext context) {
            StreamingClient ctxt = context.getOwner();

            ctxt.clientAborted();
            return;
        }

        //-------------------------------------------------------
        // Member data.
        //
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
